sudo: required

language: c

dist: bionic

services:
    - docker

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq clang-tools-6.0 curl gdb lcov libarchive-dev libc6-dev-i386 libtalloc-dev realpath sloccount strace swig uthash-dev

script:
  - sloccount --details .
  - sloccount --cached .
  - make -C src loader.exe loader-m32.exe build.h 
  - env CFLAGS=--coverage LDFLAGS='--coverage' make -C src proot care
  - env PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PWD/src make -C tests V=99
